//
//  ManagePresenter.swift
//  Weather
//
//  Created by Ерасыл Еркин on 15.05.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ManagePresentationLogic {
    func presentCityData(data: [CityData])
    func showAlert(message: String)
}

final class ManagePresenter: ManagePresentationLogic {
    weak var viewController: ManageDisplayLogic?
    
    func presentCityData(data: [CityData]) {
        viewController?.displayCityData(data: data)
    }
    
    func showAlert(message: String) {
        viewController?.displayAlert(message: message)
    }
}
