//
//  ManageRouter.swift
//  Weather
//
//  Created by Ерасыл Еркин on 15.05.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ManageRoutingLogic {
    
}

protocol ManageDataPassing {
    var dataStore: ManageDataStore? { get }
}

final class ManageRouter: NSObject, ManageRoutingLogic, ManageDataPassing {
    weak var viewController: ManageViewController?
    var dataStore: ManageDataStore?
    
}
