//
//  ManageConfigurator.swift
//  Weather
//
//  Created by Ерасыл Еркин on 15.05.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ManageConfigurator {
    
    static let shared = ManageConfigurator()
    
    func configure(viewController: ManageViewController) {
        let interactor = ManageInteractor()
        let presenter = ManagePresenter()
        let router = ManageRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
    }
}
